### PR TITLE
Make predict_input_fn compatible with TF 2.0

### PR DESCRIPTION
**Pull request by pingsutw**
`predict_input_fn` in handling_sparse_features.ipynb not work in TF 2.0

Report attribute error as :
AttributeError: 'BatchDataset' object has no attribute 'make_one_shot_iterator'

### CODE REVIEW

**Comment by ramakumar1729** [comment]
@pingsutw : Thanks for this contribution. I just saw this: I've already pushed in a similar PR. Closing this.
